version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./server:/app
        depends_on:
            - database
    database:
        image: mongo
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}
        volumes:
            - ./db/:/data/db
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - ${CLIENT_PORT}:${CLIENT_PORT}
        volumes:
            - ./client:/app
        depends_on:
            - server